# Generated by Django 5.0.1 on 2024-04-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0002_sentence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='is_red',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='is_red',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
